# Generated by Django 5.0.4 on 2024-04-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_timeinfo_post_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeinfo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userinfo',
        ),
    ]
