# Generated by Django 5.0.4 on 2024-04-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userlastviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLastViewed',
        ),
    ]
